# Site settings
title: "Music and Mind"
description: "Podcast"
podcast-description: "Movie and music podcast"
url:  "https://localhost:4000/" # Actual base url of the website
baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Pierre Le Quere"
  email: "pierrelequere2@gmail.com"
permalink: pretty
permalink: /:title
keywords: [podcast, jekyll]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
facebook:
  app_id: 
logo: /assets/img/Podcast_Cover.png
social:
  name: Pierre LE QUERE
  links:
    - https://github.com/platinarock
    - https://fr.linkedin.com/in/pierre-le-quere-4511a3161
lang: fr

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: Music and Mind
podcast_author: Pierre LE QUERE
podcast_email: pierrelequere2@gmail.com
podcast_subtitle: "Theme designed for Podcast"
podcast_summary: "Theme designed for Podcast"
podcast_description: "Theme designed for Podcast"
podcast_explicit: "no"
podcast_type: serial 
podcast_lang: fr
podcast_launch: "2022-12-01" #Launch date of your podcast
podcast_copyright: "&#xA9;Pierre LE QUERE"
podcast_feed: 
podcast_artwork: "/assets/img/Podcast_Cover.png"
